function FileName=KevinReflectedFileList(sessionType)

if strcmp(sessionType,'both')
    FileName={'ShorPert_Kevin_040215_binnedDec_ref',...
        'ShorPert_Kevin_040615_binnedDec_ref',...
        'ShorPert_Kevin_041515_binnedDec_ref',...
        'ShorPert_Kevin_042015_binnedDec_ref',...
        'ShorPert_Kevin_042315_binnedDec_ref',...
        'LongPert_Kevin_050215_binnedDec_ref',...
        'LongPert_Kevin_050415_binnedDec_ref',...
        'LongPert_Kevin_061415_binnedDec_ref'};
end


if strcmp(sessionType,'shor')
    FileName={'ShorPert_Kevin_040215_binnedDec_ref',...
        'ShorPert_Kevin_040615_binnedDec_ref',...
        'ShorPert_Kevin_041515_binnedDec_ref',...
        'ShorPert_Kevin_042015_binnedDec_ref',...
        'ShorPert_Kevin_042315_binnedDec_ref'};
end

if strcmp(sessionType,'long')
    FileName={'LongPert_Kevin_050215_binnedDec_ref',...
        'LongPert_Kevin_050415_binnedDec_ref',...
        'LongPert_Kevin_061415_binnedDec_ref'};
end



end
