% All Within Session Stats Kevin

[K_Rot_PL_AllTargetsP, K_Rot_PL_PerTargetP, K_Rot_TE_AllTargetsP, K_Rot_TE_PerTargetP,K_Rot_NS_AllTargetsP, K_Rot_NS_PerTargetP]=LearnAdaptWrapper_WithinSessionMetrics('Kevin','rot',0);
[K_Rot_PL_PerT_StatsSummary K_Rot_PL_PerT_StatsTally]=LearnAdaptWrapper_WithinSessionMetricsStatsSummary(K_Rot_PL_PerTargetP);
[K_Rot_TE_PerT_StatsSummary K_Rot_TE_PerT_StatsTally]=LearnAdaptWrapper_WithinSessionMetricsStatsSummary(K_Rot_TE_PerTargetP);
[K_Rot_NS_PerT_StatsSummary K_Rot_NS_PerT_StatsTally]=LearnAdaptWrapper_WithinSessionMetricsStatsSummary(K_Rot_NS_PerTargetP);

[K_Rot_PL_AllT_StatsSummary K_Rot_PL_AllT_StatsTally]=LearnAdaptWrapper_WithinSessionMetricsStatsSummary(K_Rot_PL_AllTargetsP);
[K_Rot_TE_AllT_StatsSummary K_Rot_TE_AllT_StatsTally]=LearnAdaptWrapper_WithinSessionMetricsStatsSummary(K_Rot_TE_AllTargetsP);
[K_Rot_NS_AllT_StatsSummary K_Rot_NS_AllT_StatsTally]=LearnAdaptWrapper_WithinSessionMetricsStatsSummary(K_Rot_NS_AllTargetsP);


[K_Ref_PL_AllTargetsP, K_Ref_PL_PerTargetP, K_Ref_TE_AllTargetsP, K_Ref_TE_PerTargetP,K_Ref_NS_AllTargetsP, K_Ref_NS_PerTargetP]=LearnAdaptWrapper_WithinSessionMetrics('Kevin','ref',0);
[K_Ref_PL_PerT_StatsSummary K_Ref_PL_PerT_StatsTally]=LearnAdaptWrapper_WithinSessionMetricsStatsSummary(K_Ref_PL_PerTargetP);
[K_Ref_TE_PerT_StatsSummary K_Ref_TE_PerT_StatsTally]=LearnAdaptWrapper_WithinSessionMetricsStatsSummary(K_Ref_TE_PerTargetP);
[K_Ref_NS_PerT_StatsSummary K_Ref_NS_PerT_StatsTally]=LearnAdaptWrapper_WithinSessionMetricsStatsSummary(K_Ref_NS_PerTargetP);

[K_Ref_PL_AllT_StatsSummary K_Ref_PL_AllT_StatsTally]=LearnAdaptWrapper_WithinSessionMetricsStatsSummary(K_Ref_PL_AllTargetsP);
[K_Ref_TE_AllT_StatsSummary K_Ref_TE_AllT_StatsTally]=LearnAdaptWrapper_WithinSessionMetricsStatsSummary(K_Ref_TE_AllTargetsP);
[K_Ref_NS_AllT_StatsSummary K_Ref_NS_AllT_StatsTally]=LearnAdaptWrapper_WithinSessionMetricsStatsSummary(K_Ref_NS_AllTargetsP);